name       : spirv-tools
version    : '2020.5'
release    : 16
source     :
    - https://github.com/KhronosGroup/SPIRV-Tools/archive/v2020.5.tar.gz : 947ee994ba416380bd7ccc1c6377ac28a4802a55ca81ccc06796c28e84c00b71
license    : Apache-2.0
component  : programming.tools
emul32     : yes
summary    : The SPIR-V Tools project provides an API and commands for processing SPIR-V modules
description: |
    The SPIR-V Tools project provides an API and commands for processing SPIR-V modules.
patterns   :
    - 32bit-devel : /usr/lib32/cmake
builddeps  :
    - spirv-headers
rundeps    :
    - devel : spirv-headers
setup      : |
    %cmake_ninja -DCMAKE_INSTALL_LIBDIR=lib%LIBSUFFIX% \
        -DSPIRV-Headers_SOURCE_DIR=%PREFIX%
build      : |
    %ninja_build
install    : |
    %ninja_install
