name       : spirv-tools
version    : 2018.3
release    : 4
source     :
    - git|https://github.com/KhronosGroup/SPIRV-Tools.git : 5f53c42a1e24e329c6e02e41cfd24a1cc0f8d22f
license    : MIT
component  : programming.tools
emul32     : yes
summary    : The SPIR-V Tools project provides an API and commands for processing SPIR-V modules
description: |
    The SPIR-V Tools project provides an API and commands for processing SPIR-V modules.
builddeps  :
    - spirv-headers
setup      : |
    mkdir -p external/spirv-headers/include
    ln -s /usr/include/spirv external/spirv-headers/include/.

    %cmake_ninja -DCMAKE_INSTALL_LIBDIR=%libdir%
build      : |
    %ninja_build
install    : |
    %ninja_install
