name       : spirv-tools
version    : 1.1
release    : 1
source     :
    - https://github.com/KhronosGroup/SPIRV-Tools/archive/spirv-1.1-rev1.tar.gz : c843441dd994b589ac23eac4b83826fe55c5823a7fcbbde6d61826494f6843b5
license    : MIT
component  : programming.tools
summary    : The SPIR-V Tools project provides an API and commands for processing SPIR-V modules.
description: |
    The SPIR-V Tools project provides an API and commands for processing SPIR-V modules.
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
