name       : spirv-tools
version    : '2020.6'
release    : 17
source     :
    - https://github.com/KhronosGroup/SPIRV-Tools/archive/v2020.6.tar.gz : de2392682df8def7ac666a2a320cd475751badf4790b01c7391b7644ecb550a3
license    : Apache-2.0
component  : programming.tools
emul32     : yes
summary    : The SPIR-V Tools project provides an API and commands for processing SPIR-V modules
description: |
    The SPIR-V Tools project provides an API and commands for processing SPIR-V modules.
patterns   :
    - 32bit-devel : /usr/lib32/cmake
builddeps  :
    - spirv-headers
rundeps    :
    - devel : spirv-headers
setup      : |
    %cmake_ninja -DCMAKE_INSTALL_LIBDIR=lib%LIBSUFFIX% \
        -DSPIRV-Headers_SOURCE_DIR=%PREFIX%
build      : |
    %ninja_build
install    : |
    %ninja_install
