name       : spirv-tools
version    : 2017.1
release    : 2
source     :
    - git|https://github.com/KhronosGroup/SPIRV-Tools.git :  efe12ff5a1b34d0e23d6a5515bfe0eb18aaa1761
license    : MIT
component  : programming.tools
summary    : The SPIR-V Tools project provides an API and commands for processing SPIR-V modules.
description: |
    The SPIR-V Tools project provides an API and commands for processing SPIR-V modules.
builddeps  :
    - spirv-headers
emul32     : yes
setup      : |
    mkdir -p external/spirv-headers/include
    ln -s /usr/include/spirv external/spirv-headers/include/.
    %cmake .
build      : |
    %make
install    : |
    %make_install
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        mv $installdir/usr/lib $installdir/usr/lib32
    fi
